version: "3.9"

services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./storage-influx:/var/lib/influxdb
    networks:
      - platojmeternet
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./storage-grafana:/var/lib/grafana
    environment:
      - GF_PATHS_CONFIG=/var/lib/grafana/custom.ini
      - GF_INSTALL_PLUGINS=marcusolsson-csv-datasource
      - GF_PLUGIN_MARCUSOLSSON_CSV_DATASOURCE_ALLOW_LOCAL_MODE=true
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    networks:
      - platojmeternet
    restart: unless-stopped

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: renderer
    ports:
      - "8081:8081"
    networks:
      - platojmeternet

  jmeter:
    image: jmeter:local
    container_name: jmeter
    volumes:
      - ./jmx:/opt/jmx
      - ./storage-grafana:/opt/grafana
      - ./report:/opt/report
    environment:
      - JMETER_VERSION=5.6.2
      - JVM_ARGS=-Xmn1024m -Xms1024m -Xmx1024m
    entrypoint: tail -f /dev/null      
    networks:
      - platojmeternet

networks:
  platojmeternet:
    name: platojmeternet
